version: "3.3"
services:
  app:
    build: .
    image: cdli-images-py
    container_name: images_docker
    command: 'tail -f /dev/null'
    volumes: 
      - type: bind
        source: ./images/
        target: /tmp/images/